### ISSUE TITLE
cool

### ISSUE THREAD

**Issue by kylezhang** [HackerHouseYT/Facebook-Newsbot#1]
Hi,
 I found your project, it's very cool,
 Dose the all videos are on YouTube？

sorry， I am a chinese.....

**Comment by atainter** [comment]
Hi @kylezhang,

Yep, all of the videos are on Youtube. Here is a link to the playlist: https://youtu.be/NUSs_2asZ1M?list=PL39pssg07dpDkbwa3-g9yIRGUunbwsTP4

Aaron

**Comment by kylezhang** [comment]
@atainter Thanks,
